name: blahagraphy
favicon: null
layout_spectrum: 0.5617021
typography_spectrum: 0.5638298
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
title: Photography by Michael Blaha
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#3C493F'
    - '#7E8D85'
    - '#B3BFB8'
    - '#F0F7F4'
    - '#A2E3C4'
  brandStrength: 0.9842688492499292
  lightness: 0.4425532
  saturation: 0.2212766
  rhythmicContrast: 0.4380338
purpose: []
